version: "3.4"
services:

  eventstore:
    image: eventstore/eventstore:release-4.1.0
    ports:
      - 2113:2113
    networks:
      - IFAS-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    command: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - IFAS-net

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    ports:
      - 127.0.0.1:5601:5601
    volumes:
      - kibanadata:/usr/share/kibana/data
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - cluster.name=docker-cluster
    networks:
      - IFAS-net

  evt-es-bridge:
    build: dotnet-event-elastic-bridge
    environment:
      - STREAM_URL=eventstore
      - ELASTIC_NAME=elasticsearch
      - EVENTSTORE_NAME=eventstore
      - USER=admin
      - PW=vEeW120SG7pSz4lbJgxCzIZh4KH16M70
      - BUFFER_SIZE=100
    networks:
      - IFAS-net

  event-generator:
    build: event-generator
    environment:
      - EVENTSTORE_NAME=eventstore
      - USER=admin
      - PW=vEeW120SG7pSz4lbJgxCzIZh4KH16M70
    networks:
      - IFAS-net

volumes:
  elasticdata:
    driver: local
  kibanadata:
    driver: local

networks:
  IFAS-net:
